// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtleadcbggplbegdzuqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bGVhZGNiZ2dwbGJlZ2R6dXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzU1ODIsImV4cCI6MjA2NjQxMTU4Mn0.ZkAN15ram1kUd78f4adLmyrCjZuILOybk9uzvqVayN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);